INSERT INTO pages (code,parentcode,pos,groupcode) VALUES ('service','homepage',1,'free');
INSERT INTO pages (code,parentcode,pos,groupcode) VALUES ('login','service',3,'free');
INSERT INTO pages (code,parentcode,pos,groupcode) VALUES ('notfound','service',1,'free');
INSERT INTO pages (code,parentcode,pos,groupcode) VALUES ('errorpage','service',2,'free');
INSERT INTO pages (code,parentcode,pos,groupcode) VALUES ('homepage','homepage',-1,'free');
INSERT INTO pages (code,parentcode,pos,groupcode) VALUES ('landing_secure','homepage',2,'bpm_broker');
INSERT INTO pages (code,parentcode,pos,groupcode) VALUES ('home_secure','homepage',3,'bpm_broker');
INSERT INTO pages (code,parentcode,pos,groupcode) VALUES ('workflow_secure','homepage',4,'bpm_broker');
INSERT INTO pages (code,parentcode,pos,groupcode) VALUES ('test','homepage',5,'free');
