INSERT INTO authuserprofiles (username,profiletype,profilexml,publicprofile) VALUES ('admin','PFL','<?xml version="1.0" encoding="UTF-8"?>
<profile id="admin" typecode="PFL" typedescr="Default user profile"><descr /><groups /><categories /><attributes><attribute name="fullname" attributetype="Monotext" /><attribute name="email" attributetype="Monotext" /></attributes></profile>
',0);
INSERT INTO authuserprofiles (username,profiletype,profilexml,publicprofile) VALUES ('jonSnow','CCD','<?xml version="1.0" encoding="UTF-8"?>
<profile id="jonSnow" typecode="CCD" typedescr="Credit Card Profile"><descr /><groups /><categories /><attributes><attribute name="name" attributetype="Monotext"><monotext>Jon</monotext></attribute><attribute name="lname" attributetype="Monotext"><monotext>Snow</monotext></attribute><attribute name="age" attributetype="Monotext"><monotext>26</monotext></attribute><attribute name="tfrdamnt" attributetype="Monotext"><monotext>600</monotext></attribute><attribute name="cStatus" attributetype="Monotext"><monotext>PLATINUM</monotext></attribute><attribute name="incCount" attributetype="Monotext"><monotext>5</monotext></attribute><attribute name="avaCredit" attributetype="Monotext"><monotext>$ 65,000</monotext></attribute><attribute name="minCredit" attributetype="Monotext"><monotext>$ 850</monotext></attribute><attribute name="crntBal" attributetype="Monotext"><monotext>$ 10,660</monotext></attribute><attribute name="lstatmentb" attributetype="Monotext"><monotext>$ 12,580</monotext></attribute><attribute name="nxtStmnt" attributetype="Monotext"><monotext>September 4th, 2018</monotext></attribute><attribute name="stateCode" attributetype="Monotext"><monotext>NY</monotext></attribute><attribute name="accntcrted" attributetype="Monotext"><monotext>Jul 14, 2013</monotext></attribute><attribute name="phone" attributetype="Monotext"><monotext>+1-541-754-3010</monotext></attribute><attribute name="email" attributetype="Monotext"><monotext>jon.snow@redhatdemo.com</monotext></attribute><attribute name="country" attributetype="Monotext"><monotext>US</monotext></attribute><attribute name="jobSector" attributetype="Monotext"><monotext>IT</monotext></attribute><attribute name="subIndstry" attributetype="Monotext"><monotext>IT Consulting</monotext></attribute></attributes></profile>
',0);
INSERT INTO authuserprofiles (username,profiletype,profilexml,publicprofile) VALUES ('khalDrogo','CCD','<?xml version="1.0" encoding="UTF-8"?>
<profile id="khalDrogo" typecode="CCD" typedescr="Credit Card Profile"><descr /><groups /><categories /><attributes><attribute name="name" attributetype="Monotext"><monotext>Khal</monotext></attribute><attribute name="lname" attributetype="Monotext"><monotext>Drogo</monotext></attribute><attribute name="age" attributetype="Monotext"><monotext>16</monotext></attribute><attribute name="tfrdamnt" attributetype="Monotext"><monotext>450</monotext></attribute><attribute name="cStatus" attributetype="Monotext"><monotext>SILVER</monotext></attribute><attribute name="incCount" attributetype="Monotext"><monotext>1</monotext></attribute><attribute name="avaCredit" attributetype="Monotext"><monotext>$ 25,450</monotext></attribute><attribute name="minCredit" attributetype="Monotext"><monotext>$ 150</monotext></attribute><attribute name="crntBal" attributetype="Monotext"><monotext>$ 8,210</monotext></attribute><attribute name="lstatmentb" attributetype="Monotext"><monotext>$ 7,180</monotext></attribute><attribute name="nxtStmnt" attributetype="Monotext"><monotext>September 8th, 2018</monotext></attribute><attribute name="stateCode" attributetype="Monotext"><monotext>VA</monotext></attribute><attribute name="accntcrted" attributetype="Monotext"><monotext>Aug 10, 2015</monotext></attribute><attribute name="phone" attributetype="Monotext"><monotext>+1-555-554-2010</monotext></attribute><attribute name="email" attributetype="Monotext"><monotext>khal.drogo@redhatdemo.com</monotext></attribute><attribute name="country" attributetype="Monotext"><monotext>US</monotext></attribute><attribute name="jobSector" attributetype="Monotext"><monotext>HR</monotext></attribute><attribute name="subIndstry" attributetype="Monotext"><monotext>HR Practices</monotext></attribute></attributes></profile>
',0);
INSERT INTO authuserprofiles (username,profiletype,profilexml,publicprofile) VALUES ('aryaStark','CCD','<?xml version="1.0" encoding="UTF-8"?>
<profile id="aryaStark" typecode="CCD" typedescr="Credit Card Profile"><descr /><groups /><categories /><attributes><attribute name="name" attributetype="Monotext"><monotext>Arya</monotext></attribute><attribute name="lname" attributetype="Monotext"><monotext>Stark</monotext></attribute><attribute name="age" attributetype="Monotext"><monotext>15</monotext></attribute><attribute name="tfrdamnt" attributetype="Monotext"><monotext>600</monotext></attribute><attribute name="cStatus" attributetype="Monotext"><monotext>GOLD</monotext></attribute><attribute name="incCount" attributetype="Monotext"><monotext>2</monotext></attribute><attribute name="avaCredit" attributetype="Monotext"><monotext>$ 55,420</monotext></attribute><attribute name="minCredit" attributetype="Monotext"><monotext>$ 1200</monotext></attribute><attribute name="crntBal" attributetype="Monotext"><monotext>$ 11,360</monotext></attribute><attribute name="lstatmentb" attributetype="Monotext"><monotext>$ 22,330</monotext></attribute><attribute name="nxtStmnt" attributetype="Monotext"><monotext>September 10th, 2018</monotext></attribute><attribute name="stateCode" attributetype="Monotext"><monotext>CA</monotext></attribute><attribute name="accntcrted" attributetype="Monotext"><monotext>Dec 22, 2016</monotext></attribute><attribute name="phone" attributetype="Monotext"><monotext>+1-434-878-9999</monotext></attribute><attribute name="email" attributetype="Monotext"><monotext>arya.stark@redhatdemo.com</monotext></attribute><attribute name="country" attributetype="Monotext"><monotext>US</monotext></attribute><attribute name="jobSector" attributetype="Monotext"><monotext>Financial Services</monotext></attribute><attribute name="subIndstry" attributetype="Monotext"><monotext>Banking</monotext></attribute></attributes></profile>
',0);
