INSERT INTO authuserprofiles (username,profiletype,profilexml,publicprofile) VALUES ('admin','PFL','<?xml version="1.0" encoding="UTF-8"?>
<profile id="admin" typecode="PFL" typedescr="Default user profile"><descr /><groups /><categories /><attributes><attribute name="fullname" attributetype="Monotext" /><attribute name="email" attributetype="Monotext" /></attributes></profile>
',0);
INSERT INTO authuserprofiles (username,profiletype,profilexml,publicprofile) VALUES ('jonSnow','CCD','<?xml version="1.0" encoding="UTF-8"?>
<profile id="jonSnow" typecode="CCD" typedescr="Credit Card Profile"><descr /><groups /><categories /><attributes><attribute name="name" attributetype="Monotext"><monotext>Jon</monotext></attribute><attribute name="lname" attributetype="Monotext"><monotext>Snow</monotext></attribute><attribute name="age" attributetype="Monotext"><monotext>26</monotext></attribute><attribute name="tfrdamnt" attributetype="Monotext"><monotext>600</monotext></attribute><attribute name="cStatus" attributetype="Monotext"><monotext>PLATINUM</monotext></attribute><attribute name="incCount" attributetype="Monotext"><monotext>5</monotext></attribute><attribute name="avaCredit" attributetype="Monotext"><monotext>$ 65,000</monotext></attribute><attribute name="minCredit" attributetype="Monotext"><monotext>$ 850</monotext></attribute><attribute name="crntBal" attributetype="Monotext"><monotext>$ 10,660</monotext></attribute><attribute name="lstatmentb" attributetype="Monotext"><monotext>$ 12,580</monotext></attribute><attribute name="nxtStmnt" attributetype="Monotext"><monotext>September 4th, 2018</monotext></attribute><attribute name="stateCode" attributetype="Monotext"><monotext>NY</monotext></attribute></attributes></profile>
',0);
INSERT INTO authuserprofiles (username,profiletype,profilexml,publicprofile) VALUES ('khalDrogo','CCD','<?xml version="1.0" encoding="UTF-8"?>
<profile id="khalDrogo" typecode="CCD" typedescr="Credit Card Profile"><descr /><groups /><categories /><attributes><attribute name="name" attributetype="Monotext"><monotext>Khal</monotext></attribute><attribute name="lname" attributetype="Monotext"><monotext>Drogo</monotext></attribute><attribute name="age" attributetype="Monotext"><monotext>16</monotext></attribute><attribute name="tfrdamnt" attributetype="Monotext"><monotext>450</monotext></attribute><attribute name="cStatus" attributetype="Monotext"><monotext>SILVER</monotext></attribute><attribute name="incCount" attributetype="Monotext"><monotext>1</monotext></attribute><attribute name="avaCredit" attributetype="Monotext"><monotext>$ 25,450</monotext></attribute><attribute name="minCredit" attributetype="Monotext"><monotext>$ 150</monotext></attribute><attribute name="crntBal" attributetype="Monotext"><monotext>$ 8,210</monotext></attribute><attribute name="lstatmentb" attributetype="Monotext"><monotext>$ 7,180</monotext></attribute><attribute name="nxtStmnt" attributetype="Monotext"><monotext>September 8th, 2018</monotext></attribute><attribute name="stateCode" attributetype="Monotext"><monotext>VA</monotext></attribute></attributes></profile>
',0);
INSERT INTO authuserprofiles (username,profiletype,profilexml,publicprofile) VALUES ('aryaStark','CCD','<?xml version="1.0" encoding="UTF-8"?>
<profile id="aryaStark" typecode="CCD" typedescr="Credit Card Profile"><descr /><groups /><categories /><attributes><attribute name="name" attributetype="Monotext"><monotext>Arya</monotext></attribute><attribute name="lname" attributetype="Monotext"><monotext>Stark</monotext></attribute><attribute name="age" attributetype="Monotext"><monotext>15</monotext></attribute><attribute name="tfrdamnt" attributetype="Monotext"><monotext>600</monotext></attribute><attribute name="cStatus" attributetype="Monotext"><monotext>GOLD</monotext></attribute><attribute name="incCount" attributetype="Monotext"><monotext>2</monotext></attribute><attribute name="avaCredit" attributetype="Monotext"><monotext>$ 55,420</monotext></attribute><attribute name="minCredit" attributetype="Monotext"><monotext>$ 1200</monotext></attribute><attribute name="crntBal" attributetype="Monotext"><monotext>$ 11,360</monotext></attribute><attribute name="lstatmentb" attributetype="Monotext"><monotext>$ 22,330</monotext></attribute><attribute name="nxtStmnt" attributetype="Monotext"><monotext>September 10th, 2018</monotext></attribute><attribute name="stateCode" attributetype="Monotext"><monotext>CA</monotext></attribute><attribute name="tranxtn" attributetype="Longtext"><text lang="en">[&#xD;
    {&#xD;
        "id": 19,&#xD;
        "recentActivity": "03/18/2017 12:23 PM",&#xD;
        "time": "12:23 PM",&#xD;
        "type": "Sale",&#xD;
        "Description": "Lowes 1452",&#xD;
        "Amount": 2.00,&#xD;
        "Balance": 22.20,&#xD;
        "extraDescriptions": [{&#xD;
            id: ''1'',&#xD;
            Transaction_Details: ''Some details'',&#xD;
            code: ''6012ABC'',&#xD;
            where_you_Paid: ''In-person transaction, Tampa, FL'',&#xD;
            description: ''Hardware and household goods'',&#xD;
            balance: ''$193.20''&#xD;
        }]&#xD;
    },&#xD;
    {&#xD;
        "id": 20,&#xD;
        "recentActivity": "03/14/2017 5:00 PM",&#xD;
        "time": "5:00 PM",&#xD;
        "type": "Payment",&#xD;
        "Description": "Payment - Web",&#xD;
        "Amount": -23.00,&#xD;
        "Balance": 232.20,&#xD;
        "extraDescriptions": [{&#xD;
            id: ''2'',&#xD;
            Transaction_Details: ''Some details'',&#xD;
            code: ''A012PMT'',&#xD;
            where_you_Paid: ''Payment - Online'',&#xD;
            description: ''Online Transaction'',&#xD;
            balance: ''$64.20''&#xD;
        }]&#xD;
    },&#xD;
    {&#xD;
        "id": 21,&#xD;
        "recentActivity": "03/13/2017 3:40 PM",&#xD;
        "time": "03:40 PM",&#xD;
        "type": "Sale",&#xD;
        "Description": "Jet.com",&#xD;
        "Amount": 101.50,&#xD;
        "Balance": 9.20,&#xD;
        "extraDescriptions": [{&#xD;
            id: ''3'',&#xD;
            Transaction_Details: ''Some details'',&#xD;
            code: ''52362TRE'',&#xD;
            where_you_Paid: ''Online transaction'',&#xD;
            description: ''General retail'',&#xD;
            balance: ''$89.20''&#xD;
        }]&#xD;
    },&#xD;
    {&#xD;
        "id": 22,&#xD;
        "recentActivity": "03/10/2017 10:48 PM",&#xD;
        "time": "10:48 PM",&#xD;
        "type": "Sale",&#xD;
        "Description": "Walmart 1445",&#xD;
        "Amount": 226.00,&#xD;
        "Balance": 5.70,&#xD;
        "extraDescriptions": [{&#xD;
            id: ''2'',&#xD;
            Transaction_Details: ''Some details'',&#xD;
            code: ''1054TPX'',&#xD;
            where_you_Paid: ''In-person transaction, Oakland, CA'',&#xD;
            description: ''General retail'',&#xD;
            balance: ''$78.70''&#xD;
        }]&#xD;
    },&#xD;
    {&#xD;
        "id": 23,&#xD;
        "recentActivity": "03/08/2017 12:23 PM",&#xD;
        "time": "12:23 PM",&#xD;
        "type": "Payment",&#xD;
        "Description": "Payment - Web",&#xD;
        "Amount": -3.00,&#xD;
        "Balance": 98.70,&#xD;
        "extraDescriptions": [{&#xD;
            id: ''3'',&#xD;
            Transaction_Details: ''Some details'',&#xD;
            code: ''0019DFT'',&#xD;
            where_you_Paid: ''Online payment'',&#xD;
            description: ''Online Transaction'',&#xD;
            balance: ''$33.70''&#xD;
        }]&#xD;
    },&#xD;
    {&#xD;
        "id": 24,&#xD;
        "recentActivity": "03/07/2017 5:00 AM",&#xD;
        "time": "5:00 AM",&#xD;
        "type": "Sale",&#xD;
        "Description": "Amazon.com",&#xD;
        "Amount": 88.00,&#xD;
        "Balance": 44.70,&#xD;
        "extraDescriptions": [{&#xD;
            id: ''2'',&#xD;
            Transaction_Details: ''Some details'',&#xD;
            code: ''0019XCD'',&#xD;
            where_you_Paid: ''Online transaction'',&#xD;
            description: ''Online retail'',&#xD;
            balance: ''$83.70''&#xD;
        }]&#xD;
    },&#xD;
    {&#xD;
        "id": 25,&#xD;
        "recentActivity": "03/04/2017 3:49 PM",&#xD;
        "time": "03:49 PM",&#xD;
        "type": "Sale",&#xD;
        "Description": "Starbucks",&#xD;
        "Amount": 764.70,&#xD;
        "Balance": 4.70,&#xD;
        "extraDescriptions": [{&#xD;
            id: ''3'',&#xD;
            Transaction_Details: ''Some details'',&#xD;
            code: ''0013FDE'',&#xD;
            where_you_Paid: ''In-person transaction, San Jose, CA'',&#xD;
            description: ''Food and Beverage'',&#xD;
            balance: ''$58.70''&#xD;
        }]&#xD;
    },&#xD;
    {&#xD;
        "id": 26,&#xD;
        "recentActivity": "03/03/2017 11:45 AM",&#xD;
        "time": "12:00 AM",&#xD;
        "type": "Sale",&#xD;
        "Description": "Caffe Savona",&#xD;
        "Amount": 6.00,&#xD;
        "Balance": 6.00,&#xD;
        "extraDescriptions": [{&#xD;
            id: ''2'',&#xD;
            Transaction_Details: ''Some details'',&#xD;
            code: ''0012ABC'',&#xD;
            where_you_Paid: ''In-person transaction, Mountain View, CA'',&#xD;
            description: ''Food and Beverage'',&#xD;
            balance: ''$50.00''&#xD;
        }]&#xD;
    },&#xD;
    {&#xD;
        "id": 27,&#xD;
        "recentActivity": "03/08/2017 11:00 AM",&#xD;
        "time": "11:00 AM",&#xD;
        "type": "Sale",&#xD;
        "Description": "Caffe Savona",&#xD;
        "Amount": 509.00,&#xD;
        "Balance": 200.00,&#xD;
        "extraDescriptions": [{&#xD;
            id: ''2'',&#xD;
            Transaction_Details: ''Some details'',&#xD;
            code: ''0012ABC'',&#xD;
            where_you_Paid: ''In-person transaction, Mountain View, CA'',&#xD;
            description: ''Food and Beverage'',&#xD;
            balance: ''$500.00''&#xD;
        }]&#xD;
    }&#xD;
]</text></attribute></attributes></profile>
',0);
